version: "3.7"
services:
  destination:
    image: training/whoami:latest
    deploy:
      replicas: 3
    networks:
      - demonet

  origin:
    image: centos:7
    command: ["sleep", "100000"] 
    networks:
      - demonet

networks:
  demonet:
    driver: overlay