apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers: 
    - name: nginx
      image: nginx:1.7.9
    - name: sidecar
      image: centos:7 
      command: ["ping"] 
      args: ["8.8.8.8"]